---
apiVersion: v1
kind: Secret
metadata:
  name: ttx-config
  namespace: ttx
type: Opaque
stringData:
  TTX_CONNECTION_STRING: ""
  TTX_SECRET_KEY: ""
  TTX_TWITCH_CLIENT_ID: ""
  TTX_TWITCH_CLIENT_SECRET: ""
  TTX_TWITCH_REDIRECT_URI: ""

---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ttx-regcreds
  namespace: ttx
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"user:token b64 encoded"}}}'